// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function Greet(arg1:string):Promise<string>;

export function LoadMappingConfig(arg1:string,arg2:string):Promise<Array<config.MappingsModel>>;

export function SelectExcelFile():Promise<string>;
